### ISSUE TITLE
Type check on array of numbers fails

### ISSUE THREAD

**Issue by blenderer** [RubenVerborgh/Chai-Things#10]
chai.should();

    var numArray = [1,2,3,4,9882];

    describe('array', function () {
        describe('numbers', function () {
            // AssertionError: expected 1 to be a number
            it('should all be numbers', function () {
                return numArray.should.all.be.a('number');
            });
        });
        describe('first number', function () {
            // Passes
            it('should be a number', function () {
                return numArray[3].should.be.a('number');
            });
        });
    });

**Comment by llopess** [comment]
+1
