### ISSUE TITLE
Type check on array of numbers fails

### ISSUE THREAD

**Issue by blenderer** [RubenVerborgh/Chai-Things#11]
Sorry about the issue#10, accidentally closed it!

    var chai = require('chai');
    require('chai-things');

    chai.should();

    var numArray = [1,2,3,4,9882];

    describe('array', function () {
        describe('elements', function () {
            it('should all be numbers', function () {
                return numArray.should.all.be.a('number');
            });
        });
        describe('first element', function () {
            it('should be a number', function () {
                return numArray[3].should.be.a('number');
            });
        });
    });

Mocha run results:

    array
      elements
        1) should all be numbers
      first element
        ✓ should be a number 

    1 passing (9ms)
    1 failing

    1) array elements should all be numbers:
       AssertionError: expected [ 1, 2, 3, 4, 9882 ] to be a number

**Comment by RubenVerborgh** [comment]
Unfortunately, using Chai-Thing with a property function is not possible at the moment, and I'm unsure whether it can be fixed easily with the current Chai design. See #4, #9, and https://github.com/RubenVerborgh/Chai-Things#known-issues.

**Comment by blenderer** [comment]
What's the difference between using:
 .should.all.match(/.*/);
and
.should.all.be.a('number')
?

**Comment by RubenVerborgh** [comment]
That works, because the test is executed on the array, not on the elements, and (the stringified version of) the array coincidentally also matches `/.*/`. It would not work with `/^\d+$/`.

**Comment by blenderer** [comment]
Makes sense. Thank you.
