### ISSUE TITLE
Error during length test

### ISSUE THREAD

**Issue by lazutkin** [RubenVerborgh/Chai-Things#12]
This snippet throws an error:

```javascript
expect([[1], [1]]).all.to.have.length(1)
```

**Comment by RubenVerborgh** [comment]
Thanks for reporting, this is a [known issue](https://github.com/RubenVerborgh/Chai-Things#known-issues).

I'm hoping for a [pull request](https://github.com/RubenVerborgh/Chai-Things/issues/4) on this, as I don't have the resources to work on this myself.
