### ISSUE TITLE
include.one not functioning correctly

### ISSUE THREAD

**Issue by omerts** [RubenVerborgh/Chai-Things#13]
Hey,

I want to check that exactly one element in an array has a certain property, and the others don't.
Unless I misunderstand the role of '.include.one', it seems to not function correctly. It looks like it is functioning as 'at least one', and not exactly one. For this we already have 'any'.
For example:
```javascript
[5, 6, 15].should.include.one.below(10);
```
Is a test which passes, even though there are two elements under 10.

Omer

**Comment by RubenVerborgh** [comment]
Hi Omer,

The functionality of `one` is to make sure that there is _at least_ one. I.e., you should read it as "does the array contain one (an) element that satisfies the conditions?".

It might be more intuitive to use the syntactical variant `some`.

Best,

Ruben
