### ISSUE TITLE
Include something that includes...

### ISSUE THREAD

**Issue by gabrielf** [RubenVerborgh/Chai-Things#9]
Maybe this construct isn't even supposed to work but since it's not mentioned in the README I was surprised:

```coffeescript
describe "the array ['abc', 'def']", ->
  array = ['abc', 'def']

  it "should include something that contain 'b'", ->
    array.should.include.something.that.contain('b')
```

Fails with:

```
  1) the array ['abc', 'def'] should include something that contain 'b':
     expected 'def' to include 'b'
```

**Comment by RubenVerborgh** [comment]
I'm afraid this is a similar case like #7. Not sure if it is fixable with the current chai design…

**Comment by gabrielf** [comment]
What a shame, because it is such a nice plugin...

Maybe the README should end with a section:

## Known issues

Because of how Chai works internally it is not possible to combine Chai Things in certain ways, see #4, #9.

**Comment by RubenVerborgh** [comment]
Yes, I'm afraid that's the best solution. Added in 352aaf638919ef177ca3cac4d25ea02eed8cb08c.
